language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
env:
  global:
    secure: Qt30kRDHO8K0F3HXLeNnrtDv6qhVsFGlEoUsX+gXUFsFAjjh3ztoaldY3Nip2qUDgvJCRV5ZrOmbFbdI3adVhMs40tNCqkG66AxSlPihbmOeIXv3Yl59SNO9WZlfnL/gUDnHOmOFCdc6wT1KpZTDQwLEtrI+En4n5ukuhxoOq+Gx8Q0bCfyfs8CnotUdGuy8xpn3DwRBrl6eOrBPXsThDUzEAS/YbEct2/gdCfxJcr5PCHPOExR1PHeGQ372yD4GpFeitraBcKfw7XCJ7SWmNbUw+nsU9diSxJ2/PFlvvWuRinNsd/RLr//ZfntnD7ihBL6XsGLCIH7Vh43aNLp+VckEnQsc25vD60zUqHhjz1iOY/v7TwtPqbBuXm+zCtbWfm3PlMWiyK/1tRhz/kqXysI1oX6pUWSG4+xM5JSJZ9PfQe255SuQcVleR2s3SreHLH+bGDZRVK85zZHQVnDMWo334fn+NwbycYc8Er2ejByAtJpWvBrxmCIcggF7xymBMYzez7Xbcd2rIMw7niDhyvkmKrihUfbYHslz8KYQtYk3QLo9YCBI4h6VuBaLNycLCHqSCxrXYQebZCw0fE7ur3x7mPfeIsdL99On+Ha8VVUQ6cGyLxUfdMmaUs2An2ADbZ8hzgBghZZTmTgHTyfq+7MbSovJjiz3fETlFPK/s2o=
