language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
env:
  matrix:
  - secure: IedGKvHUGm6DKrCNJT7kUYjsVLnBESpAxmfwWbUm3SVBDyBUkzFYvBv79tfEvxcLN9W2vri05bL1vpj3EQt+jKWm3ynIOIXtSAdtbrH6xgPL/sWfqK9WTXbKJs3ypBhuAFPaO1fIMtxHpKI98+auVLI+YKbFLQe12ltcdJmyWBtd8Hr2tMhUeAJb+1kEqN5kuB3qdFUOCg4Jl3JW4yxwvCHKlPGrP7zLkdHnszKMTHoeq6HtNgu/jv/7emrwaA9gXQxcwQAJdzd6jK3bnuSVSJK+LGADz1bwWw1I+dgK6kO/VDCqCuUfmkenufQ/RnLlhtT6LvQaWI+d8iDGcGF8tbIUWLXg4s+NjXYxRhTlCTF+QGHPKHLpaZtcbCPHbtivdDgOclXGTJLdPiJN2IDtF3HewFn84onewYpU394EE8tO30feIMVai0dQXfUr9yf2cbIo09In/zS2ilfMPmEBOBeEsukL/JIJFB/EYeaaaQ3ufZ/slFr14Hp4u6VRZZQQLOOtuosuevwPl7b+JfHc0xHE3YofQDphiZR37FZzwnurGI1o2phi8KLQeeFao5nU6ZiZfsIlt4UPm1h9Ph5qTVjR+n+TEZ7j07kEYoRIgpK4XyTRAqaTzmmplNp6v/EiZ66+F2O9kMJEqKOHIsXVKW6Hnj0/x8yvNWlyK/U9l14=
  - secure: kMivVXE+oDwP3t04349Fn/bMUiqkfqsKJgVDUI1akU8cVJgBz6pW9ysgkd0wXmlw4GJx1PmklEDGwSnUoCz9K88YTJy/M5+EQj421QrlWrLzzggOOORAzZIAoJ1IaDUtPkR42kirMh3OfeBQfSWqFCQqE1XCIFK/3SBwu6gs8mS0yCmrlw1Amjq2bEja3SXiyDl90iAP5dagyj4cmQdFJ0XDYizX0GEP0le3nRT3uN8sT6ZTRxmQur4miyl/VBlIhfT+m3K5yuhvP76kA0Bc0Gq0B42DuGgWysvT46ElrpXLgiTPvSSA29vtQgYhOPW5CVOGUFQmq/xLmCQQkeM2XgHO2MHeVVGSLrcDykV5HDhELTTTxZhUtZRuYD2Yv6tKrM/pCLlwnqcIeLHGhRN1Kckc3kr5X+dJ4bmHGh5jYMiMdqk3Lrqy7ak6eIDf3+64dc1Ecvf3hq7wjN4Jeh1dEAGadoJqDMDz4rznu/7qE7QfLnPPI00c0IHW2ZMhWYMW/0KaX9OttCsncgrfASyEA3b8zrwAYszGQR1nWtSa8twns4Ju9VvQkaEGdDtz+ghMA++wblsIy150fiiVtiEdGNs9pxdw4QEKAVT38+sn+p+aNroKk1hXpoW7dizxyc/Yy//E05il6zZBAm6Ji/gsVVjmL0PANl+rV+l6a6qQrhM=
